version: '3.4'
services:
  adminserver:
    build:
      context: .
      target: adminserver
  apigateway:
    build:
      context: .
      target: apigateway
  configserver:
    build:
      context: .
      target: configserver
  customerservice:
    build:
      context: .
      target: customerservice
  discoveryserver:
    build:
      context: .
      target: discoveryserver
  vetsservice:
    build:
      context: .
      target: vetsservice
  visitsservice:
    build:
      context: .
      target: visitsservice
